language: node_js
addons:
  apt:
    packages:
      - libconfg-2-4
cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
    - npm ci:info
notifications:
  email: false
node_js: "12"
install: echo "install happens as part of setup"
script: npm run setup
after_script: npx codecov@3
branches:
  only: ["main"]
